name: Deploy Vite App to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: install
        run: |
          cd todo-front
          npm ci

      - name: build
        run: |
          cd todo-front
          npm run build

      - name: deploy
        run: npx wrangler pages publish ./todo-front/dist
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
