name: Deploy React App to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: install
        run: |
          cd todo-front
          npm ci

      - name: build
        run: |
          cd todo-front
          npm run build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish ./todo-front/build
          wranglerVersion: 3.11.0
